___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [3]:
print (np.__version__)

1.20.3


Створити вектор з 10 елементів, заповнений одиницями:

In [4]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Створити вектор із значеннями від 0 до 10:

In [5]:
print(np.arange(11))

[ 0  1  2  3  4  5  6  7  8  9 10]


Створити матрицю 5 на 5, заповнену нулями:

In [6]:
K = (np.zeros((5, 5)))
print(K)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [15]:
K = np.random.randint(0, 5, 20)
print(K)
C = np.nonzero(K)
print(C)

[3 1 2 0 1 0 2 1 4 3 0 0 1 0 1 2 3 3 2 2]
(array([ 0,  1,  2,  4,  6,  7,  8,  9, 12, 14, 15, 16, 17, 18, 19]),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [17]:
print("Середнє значення = ", np.mean(K))
print("Медіана =", np.median(K))
print("Стандартне відхилення =", np.std(K))

Середнє значення =  1.55
Медіана = 1.5
Стандартне відхилення = 1.2031209415515967


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [31]:
A = np.random.randint(0, 3, (4, 2))
B = np.random.randint(0, 3, (2, 2))
C = A.dot(B)
print("Матриця з розміром 4х2: %s" % A)
print()
print("Матриця з розміром 2х2: %s" % B)
print()
print("Перемножені матриці: %s" % C)

Матриця з розміром 4х2: [[1 2]
 [0 0]
 [2 2]
 [0 0]]

Матриця з розміром 2х2: [[0 2]
 [1 1]]

Перемножені матриці: [[2 4]
 [0 0]
 [2 6]
 [0 0]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [46]:
a = np.reshape(C, (1, 8))
a_max = np.amax(a)

print("Матриця, що перетворена у вектор: %s" % a)
print()
print("Максимальне значення в отриманому векторі: %s" % a_max)
print()
print("Заміна у векторі за максимальним значенням:", np.where(a < a_max, a, 0))

Матриця, що перетворена у вектор: [[2 4 0 0 2 6 0 0]]

Максимальне значення в отриманому векторі: 6

Заміна у векторі за максимальним значенням: [[2 4 0 0 2 0 0 0]]


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [66]:
import matplotlib.pyplot as plt

corr_2 = np.corrcoef(C[0], C[1])
corr_3 = np.corrcoef(C[0], C[2])
corr_4 = np.corrcoef(C[0], C[3])

print("Матриця розміром 4х2 для обчислення коефіцієнту кореляції: %s" % C)
print()
print("Коефіцієнт кореляції першого рядка з другим:", corr_2)
print()
print("Коефіцієнт кореляції першого рядка з третім:", corr_3)
print()
print("Коефіцієнт кореляції першого рядка з четвертим:", corr_4)

Матриця розміром 4х2 для обчислення коефіцієнту кореляції: [[2 4]
 [0 0]
 [2 6]
 [0 0]]

Коефіцієнт кореляції першого рядка з другим: [[ 1. nan]
 [nan nan]]

Коефіцієнт кореляції першого рядка з третім: [[1. 1.]
 [1. 1.]]

Коефіцієнт кореляції першого рядка з четвертим: [[ 1. nan]
 [nan nan]]


/Users/serhiimykhalkiv/opt/anaconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2642: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/serhiimykhalkiv/opt/anaconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2643: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]


Дано матрицю. Знайти ранг матриці:

In [71]:
from numpy import linalg as LA

a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

print("Ранг матриці:", LA.matrix_rank(a))

Ранг матриці: 3


Знайти визначник матриці:

In [74]:
print("Обчислений визначник матриці:", round(LA.det(a),0))

Обчислений визначник матриці: 440.0


Знайти власні значення та власні вектори матриці: 

In [79]:
wa, va = LA.eigh(a)
print("Власні значення матриці:", wa)
print()
print("Власні вектори матриці:", va)

Власні значення матриці: [-14.30540864  -4.34740072  23.65280936]

Власні вектори матриці: [[ 0.15315575  0.88160309  0.44645191]
 [ 0.63674998 -0.43353159  0.6376518 ]
 [-0.75570681 -0.18661821  0.62775861]]


Знайдіть число, що найчастіше зустрічається в масиві:

In [84]:
a = np.random.randint(0,10,50)
d = np.argmax(np.bincount(a))
print("Згенерований вектор:", a)
print()
print("Число, що найчастіше зустрічається:", d)

Згенерований вектор: [1 3 1 5 6 2 7 5 5 9 0 7 1 8 4 0 8 7 6 3 2 5 5 9 2 6 8 2 7 4 3 1 7 0 4 7 4
 1 7 0 7 7 1 7 9 6 0 3 0 8]

Число, що найчастіше зустрічається: 7


Виведіть лише парні числа, що діляться на 5:

In [95]:
a = np.random.randint(0,10,50)
print("Згенерований випадковий вектор:", a)
print()
print("Парні числа, що ділятсья на 5:", np.where(a % 5 == 0, a, None))

Згенерований випадковий вектор: [1 4 8 2 7 2 1 7 2 2 0 5 6 8 7 9 2 8 1 9 7 2 7 0 2 4 9 3 6 5 9 0 0 3 4 3 5
 6 6 1 6 8 3 1 5 4 5 3 0 5]

Парні числа, що ділятсья на 5: [None None None None None None None None None None 0 5 None None None None
 None None None None None None None 0 None None None None None 5 None 0 0
 None None None 5 None None None None None None None 5 None 5 None 0 5]


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [99]:
M_1 = np.array([[2., 5.], [1., -10.]])
v_1 = np.array([1., 3.])
print("Обчислені x, y:", np.linalg.solve(M_1, v_1))

Обчислені x, y: [ 1.  -0.2]
